---
- name: add flatpak repository
  become: true
  flatpak_remote:
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'
    name: 'flathub'
    state: present
    method: system
    
- name: install flatpaks
  become: true
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  loop:
  - com.spotify.Client
  - org.keepassxc.KeePassXC
  - org.telegram.desktop
  - org.libreoffice.LibreOffice
  - org.qbittorrent.qBittorrent
  - org.gimp.GIMP
  - com.valvesoftware.Steam
  - org.freedesktop.Sdk.Extension.dotnet
  - com.mojang.Minecraft
  - org.gnome.eog
  - org.gnome.Evince
  - org.gnome.gedit

